#!/usr/bin/env bash

input=$1

AOC_COOKIE=`cat .cookie`

if [ -z "$input" ]; then
	echo "Please provide an argument"
	exit 1
fi

FILE="src/day${input}.zig"
if [[ -f "$FILE" ]]; then
    echo "Day $input already exists!"
	exit 1
fi

quoteRe() { sed -e 's/[^^]/[&]/g; s/\^/\\^/g; $!a\'$'\n''\\n' <<<"$1" | tr -d '\n'; }

quoteSubst() {
  IFS= read -d '' -r < <(sed -e ':a' -e '$!{N;ba' -e '}' -e 's/[&/\]/\\&/g; s/\n/\\&/g' <<<"$1")
  printf %s "${REPLY%$'\n'}"
}

test_input=$(echo "
    _ = @import(\"day${input}.zig\");
")
test_search="test {"

sed -i "/$(quoteRe "$test_search")/a $(quoteSubst "$test_input")" src/main.zig

target_input="src/inputs/day${input}.txt"
url="https://adventofcode.com/2022/day/${input}/input"
curl -o $target_input -b "$AOC_COOKIE" $url

cp template.zig src/day$input.zig
sed -i "s/dayinput/day${input}/" src/day$input.zig
